[project]
name = "cv-builder"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pyyaml>=6.0.3",
    "rendercv[full]>=2.5",
    "ruff>=0.14.10",
]
